### PR TITLE
[Docs] formatting change for docs submodule import to website source

### PR DESCRIPTION
**Pull request by usrbinkat**
These edits enable correct rendering of docs imported as a submodule into the `uor-framework/universalreference.io` website source.

Signed-off-by: usrbinkat <usrbinkat@braincraft.io>

### CODE REVIEW

**Review by afflom — APPROVED** [review]
Hi Kat. I'm excited to see this in action! Thank you!

**Review by jpower432 — APPROVED** [review]
LGTM

**Comment by sabre1041** [comment]
@usrbinkat would you be able to address the merge conflict. Then we can look to incorporate the changes here and on the website repo

**Comment by usrbinkat** [comment]
@sabre1041 done

**Pull request merged**
