### PR TITLE
feat/add render cmd and update build cmd to save collection to build cache

### LINKED ISSUE #32: [RFE] Adds the ability to cache collections on disk when pulling by attribute
**What is the problem you're trying to solve**
When a collection is pulled, it is pulled from the remote registry each time.
If the collection has been pulled in the past, it could be stored on disk and retrieved if available.
This would be most helpful when retrieving subsets of collections when pulling by attribute.

**Describe the solution you'd like**
Create a file store that stores collection by content address with the manifest stored in a place where annotations can be easily retrieved.

**Additional context**
Must implement `remotes.Resolver` interface to be used as `oras` `target.Target`.

### PR DESCRIPTION
**Pull request by jpower432**
Depends on PR #37 
Closes #32 

- [X] Docs updated
- [X] Requires an update to the Getting Started guide
- [X] Test done

# What this change does?
Adds the render command to replace the functionality of what was the build command was

Replace the build command to provide a workflow similar to the container builder 
1. Build the artifact ( It is saved to a build cache)
2. Push the artifact to a remote location
3. Optionally, pull the artifact (unpacks the files to an output directory but also pulls the artifact into the cache)

## What does this PR not do?
Provide a way to prune the cache. It currently must be deleted by the user.

### CODE REVIEW

**Review by afflom — APPROVED** [review]
Works great. The only issues that I experienced were the oras bug and I would prefer the content to only be pulled to the cache by default. Then the content could be optionally output to the target directory with the `--directory` flag.

wdyt @jpower432 ?

**Comment by jpower432** [comment]
> Works great. The only issues that I experienced were the oras bug and I would prefer the content to only be pulled to the cache by default. Then the content could be optionally output to the target directory with the `--directory` flag.
> 
> wdyt @jpower432 ?

@afflom Perhaps we can work that into a subsequent PR. If we pull into the cache only, the user has no way to retrieve the artifact from the cache with the client. If we could create a subcommand that allows the user to interact with the cache (e.g inspect or export), I would be more inclined to have this functionality on this PR.

ORAS bug fix is in PR #48

**Comment by afflom** [comment]
@sabre1041, This worked for me, over to you for final review and merge.

**Comment by jpower432** [comment]
@afflom Can you please do a quick test post-rebase and confirm the oras bug is resolved?

**Comment by afflom** [comment]
Works with the oras version bump.

**Review by sabre1041 — APPROVED** [review]

**Pull request merged**
